# SonarQube Project Configuration
sonar.projectKey=spring-boot-emsi
sonar.projectName=Spring Boot Software Engineers
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java version
sonar.java.source=17
sonar.java.target=17

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage report paths (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions (if needed)
# sonar.exclusions=**/*Application.java

